# Climber puzzle

https://fivethirtyeight.com/features/can-you-climb-your-way-to-victory/

In [17]:
from itertools import product, permutations, combinations_with_replacement
import operator
from functools import reduce
import numpy as np

In [18]:
N = 5

In [19]:
%%time
race = permutations(range(N))
all_races = combinations_with_replacement(race, r=3)
placements = np.array([[list(b) for b in a] for a in all_races])
# This array has the results for each *race*, e.g. (1,2,3...) means
# player 1 is first in race 1, player 2 second, player 3 third

CPU times: user 1.41 s, sys: 81.6 ms, total: 1.49 s
Wall time: 1.5 s


In [20]:
def score(placement):
    scores = np.ones(N, dtype=int)
    for p in placement:
        for i,c in enumerate(p):
            scores[c] *= (i+1)
    return scores

In [21]:
%%time
scores = np.array(list(map(score, placements)))
# This array has the results for each *player*, e.g. (1,1,1...) means
# player 1 is first in races 1,2,3

CPU times: user 3.01 s, sys: 40.4 ms, total: 3.05 s
Wall time: 3.06 s


In [22]:
%%time
winning_scores = np.apply_along_axis(min, 1, scores)
# This array contains the winning scores for each possible outcome

CPU times: user 711 ms, sys: 6.61 ms, total: 718 ms
Wall time: 719 ms


In [23]:
%%time
worst_winning_score = max(winning_scores)
# This is the worst winning score you can have

print(worst_winning_score)

15
CPU times: user 14.1 ms, sys: 344 µs, total: 14.5 ms
Wall time: 14.4 ms


In [24]:
# Let's find an example
example = winning_scores.argmax()
print(placements[example])
print(scores[example])

[[0 1 2 3 4]
 [2 1 3 4 0]
 [4 3 0 1 2]]
[15 16 15 24 20]
